# Generated by Django 5.2.1 on 2025-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=125, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('driving_license', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
    ]
